### ISSUE TITLE
Regolarizzare posizione nei confronti uso COOKIE

### ISSUE THREAD

**Issue by mirkochip** [mirkochip/parallax#22]
Fare presente in home page che Radio Criluge web site si avvale dell'utilizzo dei cookies.

**Comment by ZioTel** [comment]
Compare dal 2 Giugno 2015 la legge entra in vigore. Mi dispiace non averlo sollecitato. Ma adesso devo farlo perchè rischiamo una bella multa!!!  Se entro 2 Giugno 2015 non è inserito devo oscurare il sito :( questo mi dispiace

**Comment by mirkochip** [comment]
Work in progress, right now.

**Comment by mirkochip** [comment]
Inserito.
