### ISSUE TITLE
Aggiornare Copyright © 1999-2015

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#23]
Copyright © 1999-2015 anzichè Copyright © 1999-2014

PS consiglio di utilizzare codice automatico che calcola anno se si può fare, così ogni anno non cè bisogno di aggiornarlo manualmente.

**Comment by ZioTel** [comment]
SOLLECITO DA PARTE DEL TUO WEB MANAGER ;-)

**Comment by mirkochip** [comment]
Done. Managed with automatic javascript updater ;)
