### ISSUE TITLE
Aggiornare URL noteinternational.it -> noteinternational.com

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#24]
FARE SOSTITUZIONE www.noteinternational.it -> www.noteinternational.com 

INSERIRE 

<td style="text-align:center"><a href="http://www.mondocriluge.com"><img src="http://www.criluge.org/images/logo/mini/minimondocriluge.png" height="30" alt="Mondo Criluge"></a></td>

TRA IL LOGO ISOLA IN FESTA E NOTE INTERNATIONAL

**Comment by ZioTel** [comment]
AGGIORNATO CON MODIFICHE DA EFFETTUARE

**Comment by mirkochip** [comment]
Done.
