### ISSUE TITLE
Cambiare numero di telefono

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#25]
+39 345 1880828 -> + 39 393 3050607

In questo modo ci sono 2 numeri di Telefono

347 3050607 del Presidente SC Meridies
393 3050607 del Circuito Criluge

**Comment by ZioTel** [comment]
SOLLECITO DA PARTE DEL TUO WEB MANAGER ;)

**Comment by mirkochip** [comment]
Done.
