### ISSUE TITLE
Sistemiamo PICCOLE COSE per essere AGGIORNATI e PROFESSIONALI...

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#26]
Ciao compare, il mio messaggio è solo di idee, spero anche se difficile, in 5 minuti di pausa puoi sistemare il palinsensto di Radio Criluge sia nella radio e sia nella home page. 

Da più di 12 mesi alle 21 trasmettiamo sempre la stessa cosa. Questo per chi ci segue perde di professionalità, è un po' come una TV LOCALE che poi chiude trasmette lo stesso film ogni sera. Telejonica e Rete 8 hanno fatto così prima di chiudere e passare in mano di CTS.

Io inserirei alle 9.00, 14.05, 21.00, 02.05 IL MEGLIO DI FACCIA DA RADIO non solo del 2014 (manca l'ultima puntata se non sbaglio) ma anche di tutte edizione passate. Rinominare anche velocemente su sito in "Il meglio di Faccia da Radio".

Quando partirà SYRANO SICILIA TALENT prenderà lo SLOT DI IL MEGLIO DI FACCIA DA RADIO (9.00 - 14.05 - 21.00 - 02.05) così il programma finanziato e sponsorizzato nei Social dal gruppo Syrano avrà massima visibilità nell'arco di tutta la giornata. Il podcast su Syrano.it dopo una settimana della messa in onda del programma su RADIO CRILUGE.

Per IL MEGLIO DI FACCIA DA RADIO io ho pensato già da adesso di inserire IL MEGLIO DI FACCIA DA RADIO di tutte le edizioni comprese il 2014 alle 22.30 e 10.30. Già inserirlo in programmazione su RADIO CRILUGE ma non comunicarlo su home page. Quando si inserirà SYRANO SICILIA TALENT , si aggiorna anche home page con il nuovo orario per FACCIA DA RADIO delle 22.30 e 10.30.

 Per Mondo Mobile Talk ad Agosto spero di lanciare qualche iniziativa di trovare collaboratori speaker, se fallisce l'idea si chiude MMT.

**Comment by mirkochip** [comment]
Il giorno 9 luglio 2015 02:02, ZioTel <notifications@github.com> ha scritto:

> Quando partirà SYRA


Si mbare con calma valuterò le tue proposte...!

**Comment by ZioTel** [comment]
Ti mando la proposta completa del palinsensto

**Comment by ZioTel** [comment]
Creato issue nuovo dedicato https://github.com/mirkochip/parallax/issues/27
