### ISSUE TITLE
Proposta Nuovo Palinsensto 2015/2016

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#27]
06.00 22 minuti, a cura della Commissione Europea
06.30 Rotazione Musicale
07.00 LiberaMente <- NOVITA'
08.00 Rotazione Musicale <- NOVITA'
08.30 Syrano Sicilia Talent <- NOVITA'
09.00 Rotazione Musicale <- NOVITA'
10.30 Il meglio di Faccia da Radio, vecchie edizioni <- NOVITA'

12.00 Un libro per l’Europa, a cura della Commissione Europea
13.00 Rotazione Musicale
14.30 Syrano Sicilia Talent <- NOVITA'
15.00 Rotazione Musicale <- NOVITA'
15.30 La voce di Mondo in Cammino <- NOVITA'
16.00 L’interferenza senza violenza
17.00 Suoni all'Alba, a cura de L'Altoparlante
17.30 Rotazione Musicale

18.00 22 minuti, a cura della Commissione Europea
18.30 Rotazione Musicale
19.00 LiberaMente <- NOVITA'
20.00 Rotazione Musicale <- NOVITA'
20.30 Syrano Sicilia Talent <- NOVITA'
21.00 Rotazione Musicale <- NOVITA'
22.30 Il meglio di Faccia da Radio, vecchie edizioni <- NOVITA'

00.00 Un libro per l’Europa, a cura della Commissione Europea
01.00 Rotazione Musicale
02.30 Syrano Sicilia Talent <- NOVITA'
03.00 Rotazione Musicale <- NOVITA'
03.30 La voce di Mondo in Cammino <- NOVITA'
04.00 L’interferenza senza violenza
05.00 Suoni all'Alba, a cura de L'Altoparlante
05.30 Rotazione Musicale

Precisazione: Rispetto al passato non è una rivoluzione del Palinsensto ma solo un miglioramento per far entrare il nuovo programma professionale interno targato Radio Criluge ogni 6 ore. Syrano Sicilia Talent quindi andrà in onda 02.30, 08.30, 14.30, 20.30. Orario di punta per chi ascolta radio. Per Faccia da Radio una sistemazione di orario alle 10.30 e 22.30 con il meglio di tutte le edizioni anche l'ultima serie. In futuro possiamo fare anche puntate più comiche in un seconda serata tutta nostra. Ho eliminato RADIO PM AMICA perchè attualmente è sospeso. Se ritorna il suo orario o ci sarà un nuovo GR (Giornale Radio) può essere 08.00 e 20.00, in alternativa lasciamo vuoto (quindi rotazione musicale). Per IL MONDO IN CAMMINO nuovo orario 03.30 e 15.30 per equilibrare il palinsensto.

**Comment by ZioTel** [comment]
Se RADIO PA AMICA è stato sospeso, conviene comunque lasciare ultima puntata, è sempre utile. Se un giorno ritorno è presente il suo spazio. Io farei quindi così:

06.00 22 minuti, a cura della Commissione Europea
06.30 Rotazione Musicale
07.00 Mondo Mobile Talk / Cronache Buboniane 2
08.00 Syrano Sicilia Talent
09.30 La voce di Mondo in Cammino
10.00 Rotazione Musicale
10.30 Il meglio di Faccia da Radio, vecchie edizioni


12.00 Un libro per l’Europa, a cura della Commissione Europea
13.00 Radio PA Amica, a cura di Formez PA
13.05 Rotazione Musicale
14.00 Syrano Sicilia Talent
15.30 Rotazione Musicale
16.00 L’interferenza senza violenza
17.00 Suoni all'Alba, a cura de L'Altoparlante
17.30 Rotazione Musicale


18.00 22 minuti, a cura della Commissione Europea
18.30 Rotazione Musicale
19.00 Mondo Mobile Talk
20.00 Syrano Sicilia Talent
21.30 La voce di Mondo in Cammino
22.00 Rotazione Musicale
22.30 Il meglio di Faccia da Radio, vecchie edizioni

00.00 Un libro per l’Europa, a cura della Commissione Europea
01.00 Radio PA Amica, a cura di Formez PA
01.05 Rotazione Musicale
02.00 Syrano Sicilia Talent
03.30 Rotazione Musicale
04.00 L’interferenza senza violenza
05.00 Suoni all'Alba, a cura de L'Altoparlante
05.30 Rotazione Musicale

**Comment by ZioTel** [comment]
Sarebbe utile che il nuovo palisensto riesce a partire dla 19 Ottobre 2015 in occasione dei 16 anni di CRILUGE

**Comment by mirkochip** [comment]
Done.
