### ISSUE TITLE
URGENTE Trasferimento hosting

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#28]
Trasferire tutti i file presenti su www.radiocriluge.it -> www.radio.criluge.it
Inserire permalink di tutti file www.radiocriluge.it in www.radio.criluge.it (questo ci penso io!)
Un mese fa ti ho inviato i dati FTP , ho cambiato la pwd come richiesto ;)

E' importante per capire se HTML5+ funziona con il nuovo server, a breve devo effettuare dei rinnovi importanti

**Comment by mirkochip** [comment]
Certo! Inserito nei task urgenti da fare!

**Comment by ZioTel** [comment]
Perfetto. E' una pratica molto urgente da effettuare :alarm_clock:

**Comment by mirkochip** [comment]
Done.
