### ISSUE TITLE
Proposta Nuovo Palinsensto 2016/2017

### ISSUE THREAD

**Issue by ZioTel** [mirkochip/parallax#29]
06.00 Il meglio di Faccia da Radio, vecchie edizioni
07.20 Rotazione Musicale 
09.00 Suoni all'Alba, a cura de L'Altoparlante
09.30 Rotazione Musicale
10.00 Syrano Sicilia Talent
10.30 Rotazione Musicale 

12.00 La voce di Mondo in Cammino 
12.20 Rotazione Musicale
15.30 Libera...mente**
16.00 Syrano Sicilia Talent
16.30 Rotazione Musicale
17.00 L’interferenza senza violenza 

18.00 Il meglio di Faccia da Radio, vecchie edizioni
19.20 Rotazione Musicale 
21.00 Suoni all'Alba, a cura de L'Altoparlante
21.30 Rotazione Musicale
22.00 Syrano Sicilia Talent
22.30 Rotazione Musicale 

00.00 La voce di Mondo in Cammino 
00.20 Rotazione Musicale
03.30 Libera...mente**
04.00 Syrano Sicilia Talent
04.30 Rotazione Musicale
05.00 L’interferenza senza violenza 

** da sostituire con eventuale nuovo programma "Produzione Il Falco"
*** in progetto MMT alle 10 e alle 22 quando terminerà "Syrano Sicilia Talent"

**Comment by ZioTel** [comment]
06.00 Il meglio di Faccia da Radio, vecchie edizioni
07.30 Rotazione Musicale
09.00 Suoni all'Alba, a cura de L'Altoparlante
09.30 Rotazione Musicale
11.00 Syrano Sicilia Talent

12.00 La voce di Mondo in Cammino
12.30 Rotazione Musicale
14.30 Produzione "Il Falco" / Syrano Sicilia Talent
15.00 Rotazione Musicale
17.00 L’interferenza senza violenza

18.00 Il meglio di Faccia da Radio, vecchie edizioni
19.30 Rotazione Musicale
21.00 Suoni all'Alba, a cura de L'Altoparlante
21.30 Rotazione Musicale
23.00 Syrano Sicilia Talent

00.00 La voce di Mondo in Cammino
00.30 Rotazione Musicale
02.30 Produzione "Il Falco" / Syrano Sicilia Talent
03.00 Rotazione Musicale
05.00 L’interferenza senza violenza

**Comment by mirkochip** [comment]
Bisogna ammettere che il programma che usiamo per la gestione delle playlist scoraggia particolarmente l'aggiornamento. E' poco flessibile e mi ricorda le applicazioni web di Cetto la qualunque. Quanto meno il backend è stabile.. ma potrebbero anche fare qualche piccolo sforzo lato frontend, migliorandolo. Ad ogni modo... playlist aggiornate!!

**Comment by mirkochip** [comment]
Task non ancora completo in quanto bisogna aggiornare il palinsesto sul sito web.

**Comment by mirkochip** [comment]
Sito web aggiornato.
